set -g mouse on

# Unbind the default prefix (Ctrl + B)
unbind C-b

# Set Ctrl + A as the new prefix
set -g prefix C-a

# Bind Ctrl + A to send the prefix
bind C-a send-prefix

# Copy to clipboard using Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "pbcopy"

# Allow for all colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
