set -g mouse on

# Copy to clipboard using Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "wl-copy"

# Allow for all colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
